apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: orz4fjrz7-go
  janus-idp.io/tekton: orz4fjrz7-go
  backstage.io/kubernetes-id: orz4fjrz7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: orz4fjrz7-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
